CREATE DATABASE HealtClinic_Manha

CREATE TABLE TipoDeUsuario 
(
	IdTipoDeUsuario INT PRIMARY KEY IDENTITY,
	NomeTipoDeUsuario VARCHAR(50) NOT NULL
)

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoDeUsuario INT FOREIGN KEY REFERENCES TipoDeUsuario(IdTipoDeUsuario) NOT NULL,
	Nome VARCHAR(50)NOT NULL,
	Email VARCHAR(50)NOT NULL UNIQUE,
	Senha VARCHAR(20)NOT NULL
)

CREATE TABLE Especialidade
(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	NomeEspecialidade VARCHAR(100)NOT NULL
)

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR (100)NOT NULL,
	CNPJ VARCHAR(14)NOT NULL,
	NomeFantasia VARCHAR(70)NOT NULL,
	RazaoSocial VARCHAR(70)NOT NULL
)

CREATE TABLE Medico
(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica)NOT NULL,
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade)NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario)NOT NULL,
	Nome VARCHAR(50)NOT NULL,
	CRM VARCHAR(12)NOT NULL
)

CREATE TABLE Paciente
(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario)NOT NULL,
	Nome VARCHAR(50)NOT NULL,
	DataNascimento VARCHAR(10)NOT NULL,
	Telefone VARCHAR(12)NOT NULL,
	CPF VARCHAR(11)NOT NULL
)

CREATE TABLE Consulta
(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente)NOT NULL,
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico)NOT NULL,
	DataConsulta DATE NOT NULL,
	Horario TIME NOT NULL,
	Prontuario VARCHAR(256)
)

CREATE TABLE Comentario
(
	IdComentario INT PRIMARY KEY IDENTITY,
	IdConsulta INT FOREIGN KEY REFERENCES Consulta(IdConsulta)NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente)NOT NULL,
	Descricao VARCHAR(256)NOT NULL,
	Exibe BIT DEFAULT(0)
)